# Generated by Django 2.2 on 2021-01-13 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fac', '0002_facturadet_facturaenc'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facturadet',
            options={'permissions': [('sup_caja_facturadet', 'Permisos de supervisor de caja detalle')], 'verbose_name': 'Detalle factura', 'verbose_name_plural': 'Detalles facturas'},
        ),
        migrations.AlterModelOptions(
            name='facturaenc',
            options={'permissions': [('sup_caja_facturaenc', 'Permisos de supervisor de caja encabezado')], 'verbose_name': 'Encabezado factura', 'verbose_name_plural': 'Encabezado facturas'},
        ),
    ]
